//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentClinicApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokumenty
    {
        public int IdDokumentu { get; set; }
        public int IdPacjenta { get; set; }
        public string NazwaDokumentu { get; set; }
        public string TypDokumentu { get; set; }
        public string Opis { get; set; }
        public System.DateTime DataDodania { get; set; }
        public string SciezkaDoPliku { get; set; }
    
        public virtual Pacjenci Pacjenci { get; set; }
    }
}
