//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentClinicApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrafikPracownikow
    {
        public int IdGrafiku { get; set; }
        public int IdPracownika { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan GodzinaRozpoczęcia { get; set; }
        public System.TimeSpan GodzinaZakończenia { get; set; }
    
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
