//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentClinicApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaLeczenia
    {
        public int IdHistorii { get; set; }
        public int IdPacjenta { get; set; }
        public int IdPracownika { get; set; }
        public System.DateTime Data { get; set; }
        public string OpisLeczenia { get; set; }
        public string Zalecenia { get; set; }
    
        public virtual Pacjenci Pacjenci { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
