//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentClinicApp.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DentCareEntities : DbContext
    {
        public DentCareEntities()
            : base("name=DentCareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dokumenty> Dokumenty { get; set; }
        public virtual DbSet<GrafikPracownikow> GrafikPracownikow { get; set; }
        public virtual DbSet<HistoriaLeczenia> HistoriaLeczenia { get; set; }
        public virtual DbSet<Leki> Leki { get; set; }
        public virtual DbSet<LogiAktywnosci> LogiAktywnosci { get; set; }
        public virtual DbSet<Notatki> Notatki { get; set; }
        public virtual DbSet<Pacjenci> Pacjenci { get; set; }
        public virtual DbSet<Platnosci> Platnosci { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<Recepty> Recepty { get; set; }
        public virtual DbSet<ReceptyLeki> ReceptyLeki { get; set; }
        public virtual DbSet<Stanowiska> Stanowiska { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uslugi> Uslugi { get; set; }
        public virtual DbSet<UzytkownicySystemu> UzytkownicySystemu { get; set; }
        public virtual DbSet<Wizyty> Wizyty { get; set; }
    }
}
