//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentClinicApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notatki
    {
        public int IdNotatki { get; set; }
        public int IdPacjenta { get; set; }
        public System.DateTime Data { get; set; }
        public string Tekst { get; set; }
        public Nullable<int> IdPracownika { get; set; }
    
        public virtual Pacjenci Pacjenci { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
