//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentClinicApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platnosci
    {
        public int IdPlatnosci { get; set; }
        public int IdWizyty { get; set; }
        public Nullable<System.DateTime> DataPlatnosci { get; set; }
        public decimal Kwota { get; set; }
        public string MetodaPlatnosci { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> IdPacjenta { get; set; }
        public Nullable<int> IdPracownika { get; set; }
        public Nullable<int> IdUzytkownika { get; set; }
        public Nullable<int> IdUslugi { get; set; }
    
        public virtual Wizyty Wizyty { get; set; }
        public virtual Wizyty Wizyty1 { get; set; }
        public virtual Pacjenci Pacjenci { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual UzytkownicySystemu UzytkownicySystemu { get; set; }
        public virtual Uslugi Uslugi { get; set; }
    }
}
