//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentClinicApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptyLeki
    {
        public int IdReceptyLeki { get; set; }
        public int IdRecepty { get; set; }
        public int IdLeku { get; set; }
        public int Ilosc { get; set; }
        public string Uwagi { get; set; }
        public System.DateTime DataDodania { get; set; }
    
        public virtual Leki Leki { get; set; }
        public virtual Recepty Recepty { get; set; }
    }
}
