//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentClinicApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wizyty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wizyty()
        {
            this.Platnosci = new HashSet<Platnosci>();
            this.Platnosci1 = new HashSet<Platnosci>();
        }
    
        public int IdWizyty { get; set; }
        public int IdPacjenta { get; set; }
        public int IdPracownika { get; set; }
        public int IdUslugi { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan Godzina { get; set; }
        public string Status { get; set; }
        public int CzasTrwaniaWizyty { get; set; }
    
        public virtual Pacjenci Pacjenci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Platnosci> Platnosci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Platnosci> Platnosci1 { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Uslugi Uslugi { get; set; }
    }
}
